### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-diagnostics#1]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

---

Originally posted by @makasim at https://github.com/zendframework/zend-diagnostics/issues/85

**Comment by Ocramius** [comment]
Very much **for** this change, but in the form of a pull request, rather than a TODO item.

Closing here, as it won't be actively worked on by maintainers of the library.
