### ISSUE TITLE
Use an assertion library for parameter validation in checks

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-diagnostics#2]
Like https://packagist.org/packages/beberlei/assert or https://packagist.org/packages/peridot-php/leo

I would be happy to provide a PR if you accept such a contribution.

---

Originally posted by @sagikazarmark at https://github.com/zendframework/zend-diagnostics/issues/51

**Comment by Ocramius** [comment]
Closing here: assertion libraries are implementation details.

A patch is still welcome, should it be needed.
