### ISSUE TITLE
conflict with zenddiagnostics

### ISSUE THREAD

**Issue by mikeSimonson** [laminas/laminas-diagnostics#3]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.6.0

#### Summary

I am running php 7.2.22 with composer 1.9.3.
I have a project that require the package https://packagist.org/packages/liip/monitor-bundle#2.11.2
That package requires zendframework/zenddiagnostics ^1.5.

#### Current behavior

Somehow laminas-diagnostics is installed in version 1.6.
Code in the monitor-bundle breaks because it can't load the ZendDiagnostics\Runner\Reporter\ReporterInterface.
When I run composer why laminas/laminas-diagnostics it points to the liip/monitor-bundle.

I fail to undestand how laminas gets installed while the composer.json for liip/monitor-bundle version 2.11.2 never mention it. It explicitly requires zendframework/zenddiagnostics ^1.5.

Any idea what's going on ?

I fixed the issue by forcing the oro/health-check-bundle to install the liip/monitor-bundle v2.12.1 which require laminas. But I still want to figure out why the install with the version 2.11.2 of the package fails ( it install laminas but still use some zendframework interfaces)

#### How to reproduce

Installing the package oro/health-check-bundle in version 3.1.5 should trigger the same issue.

#### Expected behavior

That package zendframework/zenddiagnostics should be installed.

**Comment by MadCat34** [comment]
LiipMonitorBundle 2.12.0 has migrate to Laminas-Diagnostics :-)

https://github.com/liip/LiipMonitorBundle/blob/master/UPGRADE.md

**Comment by samsonasik** [comment]
closing as @MadCat34 state that LiipMonitorBundle 2.12.0 migrated to use laminas-diagnostics. Please re-create issue if problem persist.
