### ISSUE TITLE
The dependency enlightn/security-checker should be in the require and not in the require dev of Compoer.

### ISSUE THREAD

**Issue by nayzo** [laminas/laminas-diagnostics#49]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master and 1.15.0

#### Summary

The dependency `enlightn/security-checker` should be in the `require` and not in the `require-dev` of Compoer.

#### Current behavior

After a `composer update`, I get this error: 
`Unable to find "Enlightn\SecurityChecker\AdvisoryAnalyzer" class. Please install "enlightn/security-checker" library to use this Check.`

Could you plz set the enlightn/security-checker dependency in the require part of composer. 
Thnaks

**Comment by Ocramius** [comment]
Send a patch!

**Comment by nayzo** [comment]
@Ocramius Done.
cf: https://github.com/laminas/laminas-diagnostics/pull/50

**Comment by Ocramius** [comment]
Thanks @nayzo!
