### ISSUE TITLE
Adds support for doctrine/migrations 3.0

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-diagnostics#7]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

[`doctrine/migrations` 3.0](https://github.com/doctrine/migrations/releases/tag/3.0.0) has been released, so we'd need to add support for it here

**Comment by Ocramius** [comment]
Had a quick glance:

https://github.com/laminas/laminas-diagnostics/blob/2f4ebe9517028b0b8b272fd844f0b92628824781/src/Check/DoctrineMigration.php#L38-L39

The API used here is no longer in `3.0`: probably moved to a different endpoint

**Comment by cgrabenstein** [comment]
I added a PR that introduces support of v3, though at the same time breaking support of v2. As I wrote in the PR, I need some help in how to support both versions, then I'll gladly finalize it.
